modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="forged_reactor"
version="1.0.0"
displayName="Forged Reactor Mod"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Maketendo, Westankrang"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.forged_reactor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.forged_reactor]]
    modId="playeranimator"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration